main:
  components_repository: "https://github.com/HordonezB/MGEHOB_20240127.git"
  project_name: MGEHOB_20240127
  steps: all
  val_size: 0.2
  test_size: 0.2

modeling:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    random_state: 42
